<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Footprint_Background</AssemblyName>
    <RootNamespace>Footprint.Background</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Footprint_Core/Footprint_Core.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsolatedBackgroundBuild)' == 'true'">
    <ProjectReference Update="../Footprint_Core/Footprint_Core.csproj">
      <AdditionalProperties>PlatformTarget=AnyCPU;BaseOutputPath=$([System.IO.Path]::GetFullPath('$(BaseOutputPath)core/output/'));BaseIntermediateOutputPath=$([System.IO.Path]::GetFullPath('$(BaseIntermediateOutputPath)core/intermediate/'));MSBuildProjectExtensionsPath=$([System.IO.Path]::GetFullPath('$(BaseIntermediateOutputPath)core/intermediate/'));DefaultItemExcludes=obj/**;IsolatedBackgroundBuild=true</AdditionalProperties>
      <SetPlatform>Platform=AnyCPU</SetPlatform>
    </ProjectReference>
  </ItemGroup>
</Project>
