<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Footprint_Agent</AssemblyName>
    <RootNamespace>Footprint.Worker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Footprint_Core/Footprint_Core.csproj" />
  </ItemGroup>
</Project>
